<!-- Header -->
<section id="header">
  <header>
    <h1><?php echo $this->getConfig('HeaderTitle') ?></h1>
    <p>Mancano</p>
    <div id="clockdiv">
      <div>
        <span class="days"></span>
        <div class="smalltext">Giorni</div>
      </div>
      <div>
        <span class="hours"></span>
        <div class="smalltext">Ore</div>
      </div>
      <div>
        <span class="minutes"></span>
        <div class="smalltext">Minuti</div>
      </div>
      <div>
        <span class="seconds"></span>
        <div class="smalltext">Secondi</div>
      </div>
    </div>
  </header>
  <footer>
    <a href="#banner" class="button style2 scrolly-middle">Davvero??</a>
  </footer>
</section>