<?php

add_action('after_setup_theme', 'remove_admin_bar');

function remove_admin_bar()
{
    show_admin_bar(false);
}

if (function_exists('register_field_group')) {
    register_field_group(array(
      'id' => 'acf_home-page-fields',
      'title' => 'Home Page Fields',
      'fields' => array(
          array(
              'key' => 'field_56b0aa1e8effd',
              'label' => 'Inizio',
              'name' => '',
              'type' => 'tab',
          ),
          array(
              'key' => 'field_56b0a9b38effb',
              'label' => 'Titolo',
              'name' => 'hp_first_titolo',
              'type' => 'text',
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_56b0a9d68effc',
              'label' => 'Data dell\'evento',
              'name' => 'hp_first_data',
              'type' => 'text',
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_56b0aab98f002',
              'label' => 'Mancano',
              'name' => 'hp_first_mancano',
              'type' => 'text',
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_56b0aa2e8effe',
              'label' => 'Testo pulsante scroll',
              'name' => 'hp_first_pulsante_scroll',
              'type' => 'text',
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_56b0aa6f8efff',
              'label' => 'Seconda parte',
              'name' => '',
              'type' => 'tab',
          ),
          array(
              'key' => 'field_56b0aa8b8f000',
              'label' => 'Titolo',
              'name' => 'hp_second_titolo',
              'type' => 'text',
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_56b0aaa08f001',
              'label' => 'Descrizione',
              'name' => 'hp_second_descrizione',
              'type' => 'textarea',
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => '',
              'formatting' => 'br',
          ),
          array(
              'key' => 'field_56b0aad08f003',
              'label' => 'Testo pulsante scroll',
              'name' => 'hp_second_pulsante_scroll',
              'type' => 'text',
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_56b0aaf68f004',
              'label' => 'Informazioni',
              'name' => '',
              'type' => 'tab',
          ),
          array(
              'key' => 'field_56b0ab018f005',
              'label' => 'Elenco boxes',
              'name' => 'hp_info_elenco_boxes',
              'type' => 'repeater',
              'sub_fields' => array(
                  array(
                      'key' => 'field_56b0ac53ca41c',
                      'label' => 'Stile',
                      'name' => 'hp_boxes_stile',
                      'type' => 'radio',
                      'column_width' => '',
                      'choices' => array(
                          'style1' => 'Piccolo',
                          'style2' => 'Grande',
                      ),
                      'other_choice' => 0,
                      'save_other_choice' => 0,
                      'default_value' => '',
                      'layout' => 'horizontal',
                  ),
                  array(
                      'key' => 'field_56b0b091ca41d',
                      'label' => 'Allineamento',
                      'name' => 'hp_boxes_allineamento',
                      'type' => 'checkbox',
                      'conditional_logic' => array(
                          'status' => 1,
                          'rules' => array(
                              array(
                                  'field' => 'field_56b0ac53ca41c',
                                  'operator' => '==',
                                  'value' => 'style1',
                              ),
                          ),
                          'allorany' => 'all',
                      ),
                      'column_width' => '',
                      'choices' => array(
                          'right' => 'Destra',
                          'left' => 'Sinistra',
                      ),
                      'default_value' => '',
                      'layout' => 'horizontal',
                  ),
                  array(
                      'key' => 'field_56b0b0f6ca41e',
                      'label' => 'Titolo',
                      'name' => 'hp_boxes_header',
                      'type' => 'text',
                      'column_width' => '',
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'formatting' => 'html',
                      'maxlength' => '',
                  ),
                  array(
                      'key' => 'field_56b0b121ca41f',
                      'label' => 'Descrizione Titolo',
                      'name' => 'hp_boxes_descrizione_titolo',
                      'type' => 'textarea',
                      'conditional_logic' => array(
                          'status' => 1,
                          'rules' => array(
                              array(
                                  'field' => 'field_56b0ac53ca41c',
                                  'operator' => '==',
                                  'value' => 'style2',
                              ),
                          ),
                          'allorany' => 'all',
                      ),
                      'column_width' => '',
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'formatting' => 'html',
                      'maxlength' => '',
                  ),
                  array(
                      'key' => 'field_56b0b15cca420',
                      'label' => 'Immagine',
                      'name' => 'hp_boxes_immagine',
                      'type' => 'image',
                      'conditional_logic' => array(
                          'status' => 1,
                          'rules' => array(
                              array(
                                  'field' => 'field_56b0ac53ca41c',
                                  'operator' => '==',
                                  'value' => 'style1',
                              ),
                          ),
                          'allorany' => 'all',
                      ),
                      'column_width' => '',
                      'save_format' => 'url',
                      'preview_size' => 'thumbnail',
                      'library' => 'all',
                  ),
                  array(
                      'key' => 'field_56b0b197ca421',
                      'label' => 'Testo interno',
                      'name' => 'hp_boxes_testo_interno',
                      'type' => 'textarea',
                      'conditional_logic' => array(
                          'status' => 1,
                          'rules' => array(
                              array(
                                  'field' => 'field_56b0ac53ca41c',
                                  'operator' => '==',
                                  'value' => 'style1',
                              ),
                          ),
                          'allorany' => 'all',
                      ),
                      'column_width' => '',
                      'default_value' => '',
                      'placeholder' => '',
                      'maxlength' => '',
                      'rows' => '',
                      'formatting' => 'html',
                  ),
                  array(
                      'key' => 'field_56b0bb134f3f2',
                      'label' => 'Gallery di immagini',
                      'name' => 'hp_boxes_gallery',
                      'type' => 'repeater',
                      'conditional_logic' => array(
                          'status' => 1,
                          'rules' => array(
                              array(
                                  'field' => 'field_56b0ac53ca41c',
                                  'operator' => '==',
                                  'value' => 'style2',
                              ),
                          ),
                          'allorany' => 'all',
                      ),
                      'column_width' => '',
                      'sub_fields' => array(
                          array(
                              'key' => 'field_56b0bb3c4f3f3',
                              'label' => 'Immagine',
                              'name' => 'hp_boxes_gallery_image',
                              'type' => 'image',
                              'column_width' => '',
                              'save_format' => 'object',
                              'preview_size' => 'thumbnail',
                              'library' => 'all',
                          ),
                      ),
                      'row_min' => '',
                      'row_limit' => '',
                      'layout' => 'row',
                      'button_label' => 'Add Row',
                  ),
              ),
              'row_min' => '',
              'row_limit' => '',
              'layout' => 'row',
              'button_label' => 'Aggiungi box informazioni',
          ),
      ),
      'location' => array(
          array(
              array(
                  'param' => 'page_template',
                  'operator' => '==',
                  'value' => 'page-templates/home.php',
                  'order_no' => 0,
                  'group_no' => 0,
              ),
          ),
      ),
      'options' => array(
          'position' => 'normal',
          'layout' => 'default',
          'hide_on_screen' => array(
              0 => 'permalink',
              1 => 'the_content',
              2 => 'excerpt',
              3 => 'custom_fields',
              4 => 'discussion',
              5 => 'comments',
              6 => 'revisions',
              7 => 'slug',
              8 => 'author',
              9 => 'format',
              10 => 'featured_image',
              11 => 'categories',
              12 => 'tags',
              13 => 'send-trackbacks',
          ),
      ),
      'menu_order' => 0,
  ));
}
